site_name: Decred Developer Documentation
theme: 
  name: material
  favicon: 'img/favicon.ico?v=s3ss'
  logo: 'img/decred_logo_symbol_128.svg'
  font: false
  features:
    - instant
  icon:
    repo: octicons/mark-github-16
extra:
  social:
    - icon: octicons/mark-github-16
      link: https://github.com/decred
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/decredproject
    - icon: fontawesome/brands/medium
      link: https://medium.com/decred
    - icon: fontawesome/brands/reddit
      link: https://www.reddit.com/r/decred/
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/decredchannel
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/decredproject/
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/decredproject/
    - icon: fontawesome/brands/weibo
      link: https://weibo.com/DecredProject
repo_url: https://github.com/decred/dcrdevdocs
repo_name: decred/dcrdevdocs
markdown_extensions:
  - markdown.extensions.footnotes
  - markdown.extensions.smarty
  - markdown.extensions.admonition
  - markdown.extensions.toc:
      permalink: True
  - markdown.extensions.tables
  - pymdownx.details
  - pymdownx.arithmatex
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
extra_javascript:
  - js/MathJax-2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML
extra_css:
  - css/fonts.css
  - css/style.css
plugins:
  - markdownextradata
  - search
nav:
- 'Home': 'index.md'
- 'Projects': 'projects.md'
- Core Blockchain Concepts:
  - 'Blockchain': 'core-blockchain-concepts/blockchain.md'
  - Proof-of-Stake (PoS):
    - 'Stake Enabled Height (SEH)': 'core-blockchain-concepts/proof-of-stake/stake-enabled-height.md'
    - 'Stake Validation Height (SVH)': 'core-blockchain-concepts/proof-of-stake/stake-validation-height.md'
- Developer Guides:
  - Transactions:
    - 'Transactions': 'developer-guides/transactions/transactions.md'
    - 'Transaction Format': 'developer-guides/transactions/transaction-format.md' 
    - 'Transaction Extensions': 'developer-guides/transactions/transaction-extensions.md'
  - Wallets:
    - 'Overview': 'developer-guides/wallets/overview.md'
    - 'Seed Generation Process': 'developer-guides/wallets/mnemonic-seed.md'
    - 'Deterministic Wallet Formats': 'developer-guides/wallets/deterministic-wallet-formats.md'
  - 'Addresses': 'developer-guides/addresses.md'
  - 'Blockchain Parameters': 'developer-guides/blockchain-parameters.md'
  - 'Block Header Specifications': 'developer-guides/block-header-specifications.md'
  - 'Script Extensions': 'developer-guides/script-extensions.md'
  - 'Merkle Root Construction': 'developer-guides/merkle-root-construction.md'
  - 'Ticket Selection': 'developer-guides/ticket-selection.md'
- Protocol / Peer-to-Peer (P2P) Network:
  - 'Peer Discovery': 'protocol-p2p-network/peer-discovery.md'
  - 'Initial Block Download': 'protocol-p2p-network/initial-block-download.md'
  - 'Orphan Blocks': 'protocol-p2p-network/orphan-blocks.md'
  - 'Transaction Broadcasting': 'protocol-p2p-network/transaction-broadcasting.md'
  - 'Memory Pool': 'protocol-p2p-network/memory-pool.md'
- Environments:
  - 'Mainnet': 'environments/mainnet.md'
  - 'Testnet': 'environments/testnet.md'
  - 'Simnet': 'environments/simnet.md'
  - 'Regnet': 'environments/regnet.md'
- Contributing:
  - 'Contributor Guidelines': 'contributing/contributor-guidelines.md'
copyright: If you wish to improve this site, please <a href="https://github.com/decred/dcrdevdocs/issues/new"><i class="fa fa-github"></i> open an issue</a> or <a href="https://github.com/decred/dcrdevdocs/compare"><i class="fa fa-github"></i> send a pull request</a>.<br>dcrdevdocs v0.0.1. Decred Project 2019.
